/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#1296db',
          light: '#4fb0e8',
          dark: '#0d7ab3',
          bg: '#e8f4fc',
        },
        white: '#ffffff',
        'bg-page': '#f5f6f7',
        'bg-card': '#ffffff',
        'bg-hover': '#f0f2f5',
        'bg-active': '#e8f4fc',
        'text-primary': '#1f2329',
        'text-secondary': '#646a73',
        'text-placeholder': '#8f959e',
        'text-disabled': '#bbbfc4',
        border: '#dee0e3',
        'border-light': '#e5e6eb',
        success: '#34c724',
        warning: '#ff9800',
        error: '#f54a45',
        info: '#1296db',
        // Agent colors
        'agent-tiandao': '#1890ff',
        'agent-writer': '#52c41a',
        'agent-worldguardian': '#fa8c16',
        'agent-liuheping': '#eb2f96',
        'agent-planner': '#722ed1',
        'agent-reviewer': '#13c2c2',
        'agent-observer': '#faad14',
        'agent-researcher': '#595959',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        sm: '4px',
        base: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      fontSize: {
        xs: '12px',
        sm: '13px',
        base: '14px',
        lg: '16px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '30px',
      },
      lineHeight: {
        tight: '1.25',
        base: '1.5',
        relaxed: '1.75',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          '"Helvetica Neue"',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          '"SF Mono"',
          '"Fira Code"',
          '"JetBrains Mono"',
          'Consolas',
          '"Liberation Mono"',
          'Menlo',
          'monospace',
        ],
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },
    },
  },
  plugins: [],
}
